[package]
org = "crates"
name = "file"
version = "1.0.1"
keywords = ["file", "read"]
repository = "https://github.com/MohamedSabthar/file"
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.crates"
path = "../native/build/libs/file-native-1.0-SNAPSHOT.jar"

[build-options]
observabilityIncluded = true
