[package]
org = "crates"
name = "file"
version = "0.1.0"
distribution = "2201.6.0-20230525-070000-e36fc7ac"

[[platform.java11.dependency]]
groupId = "io.crates"
path = "../native/build/libs/file-native-1.0-SNAPSHOT.jar"

[build-options]
observabilityIncluded = true
